DROP SCHEMA IF EXISTS museu_esquema CASCADE;
CREATE SCHEMA museu_esquema;

SET search_path TO museu_esquema;

CREATE TABLE COLECCIO (
    nom_col VARCHAR(100) NOT NULL,
    direccio VARCHAR(255) NOT NULL,
    telefon VARCHAR(20),
    CONSTRAINT PK_COLLECCIO PRIMARY KEY (nom_col)
);

CREATE TABLE ESTIL_PICTORIC (
    nom_estil VARCHAR(100) NOT NULL,
    data_ini DATE NOT NULL,
    data_fi DATE,
    CONSTRAINT PK_ESTIL PRIMARY KEY (nom_estil)
);

CREATE TABLE PINTOR (
    pintor_id INTEGER NOT NULL,
    nom VARCHAR(100) NOT NULL,
    nom_artistic VARCHAR(100),
    nacionalitat VARCHAR(50) NOT NULL,
    data_naixement DATE,
    data_mort DATE,
    CONSTRAINT PK_PINTOR PRIMARY KEY (pintor_id)
);

CREATE TABLE PERSONAL (
    dni CHAR(9) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    cognoms VARCHAR(100) NOT NULL,
    telefon VARCHAR(20) NOT NULL,
    data_contractacio DATE NOT NULL,
    CONSTRAINT PK_PERSONAL PRIMARY KEY (dni)
);

CREATE TABLE CONSERVADOR (
    dni CHAR(9) NOT NULL,
    especialitat_doctorat VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CONSERVADOR PRIMARY KEY (dni),
    CONSTRAINT FK_CONS_PER FOREIGN KEY (dni) REFERENCES PERSONAL(dni) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE RESTAURADOR (
    dni CHAR(9) NOT NULL,
    CONSTRAINT PK_RESTAURADOR PRIMARY KEY (dni),
    CONSTRAINT FK_REST_PER FOREIGN KEY (dni) REFERENCES PERSONAL(dni) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE QUADRE (
    codi_quadre INTEGER NOT NULL,
    tecnica VARCHAR(50) NOT NULL,
    data_pintat DATE NOT NULL,
    nom_estil VARCHAR(100),
    CONSTRAINT PK_QUADRE PRIMARY KEY (codi_quadre),
    CONSTRAINT FK_QUADRE_ESTIL FOREIGN KEY (nom_estil) REFERENCES ESTIL_PICTORIC(nom_estil) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE COLECCIO_TEMPORAL (
    titol_temporal VARCHAR(100) NOT NULL,
    data_ini DATE NOT NULL,
    data_fi DATE,
    dni_conservador CHAR(9) NOT NULL,
    CONSTRAINT PK_COL_TEMP PRIMARY KEY (titol_temporal),
    CONSTRAINT FK_TEMP_CONS FOREIGN KEY (dni_conservador) REFERENCES CONSERVADOR(dni) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EXTERN (
    codi_quadre INTEGER NOT NULL,
    nom_propietari VARCHAR(100) NOT NULL,
    telefon_contacte VARCHAR(20) NOT NULL,
    pais_origen VARCHAR(50) NOT NULL,
    titol_temporal VARCHAR(100),
    CONSTRAINT PK_EXTERN PRIMARY KEY (codi_quadre),
    CONSTRAINT FK_EXTERN_QUADRE FOREIGN KEY (codi_quadre) REFERENCES QUADRE(codi_quadre) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_EXTERN_TEMP FOREIGN KEY (titol_temporal) REFERENCES COLECCIO_TEMPORAL(titol_temporal) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PROPI (
    codi_quadre INTEGER NOT NULL,
    valor DECIMAL(12,2) NOT NULL,
    restauracio BOOLEAN NOT NULL,
    any_arribada INTEGER NOT NULL,
    pintor_id INTEGER,
    CONSTRAINT PK_PROPI PRIMARY KEY (codi_quadre),
    CONSTRAINT FK_PROPI_QUADRE FOREIGN KEY (codi_quadre) REFERENCES QUADRE(codi_quadre) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_PROPI_PINTOR FOREIGN KEY (pintor_id) REFERENCES PINTOR(pintor_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PLANTA (
    num_planta INTEGER NOT NULL,
    aforament_maxim INTEGER NOT NULL,
    CONSTRAINT PK_PLANTA PRIMARY KEY (num_planta)
);

CREATE TABLE SALA (
    num_planta INTEGER NOT NULL,
    num_sala INTEGER NOT NULL,
    max_quadres INTEGER NOT NULL,
    CONSTRAINT PK_SALA PRIMARY KEY (num_planta, num_sala),
    CONSTRAINT FK_SALA_PLANTA FOREIGN KEY (num_planta) REFERENCES PLANTA(num_planta) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE RESTAURA (
    codi_quadre INTEGER NOT NULL,
    dni_restaurador CHAR(9) NOT NULL,
    data_ini DATE NOT NULL,
    data_fi DATE,
    CONSTRAINT PK_RESTAURA PRIMARY KEY (codi_quadre, dni_restaurador, data_ini),
    CONSTRAINT FK_RES_PROPI FOREIGN KEY (codi_quadre) REFERENCES PROPI(codi_quadre) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_RES_REST FOREIGN KEY (dni_restaurador) REFERENCES RESTAURADOR(dni) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE POT_REST (
    dni_restaurador CHAR(9) NOT NULL,
    pintor_id INTEGER NOT NULL,
    CONSTRAINT PK_POT_REST PRIMARY KEY (dni_restaurador, pintor_id),
    CONSTRAINT FK_POT_REST_REST FOREIGN KEY (dni_restaurador) REFERENCES RESTAURADOR(dni) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_POT_REST_PINT FOREIGN KEY (pintor_id) REFERENCES PINTOR(pintor_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EXPONE (
    codi_quadre INTEGER NOT NULL,
    num_planta INTEGER NOT NULL,
    num_sala INTEGER NOT NULL,
    data_ini DATE NOT NULL,
    data_fi DATE,
    CONSTRAINT PK_EXPONE PRIMARY KEY (codi_quadre, num_planta, num_sala, data_ini),
    CONSTRAINT FK_EXP_PROPI FOREIGN KEY (codi_quadre) REFERENCES PROPI(codi_quadre) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_EXP_SALA FOREIGN KEY (num_planta, num_sala) REFERENCES SALA(num_planta, num_sala) ON UPDATE CASCADE ON DELETE RESTRICT
);
