DROP SCHEMA IF EXISTS ong_esquema CASCADE;
CREATE SCHEMA ong_esquema;

SET search_path TO ong_esquema;

CREATE TYPE sexe_enum AS ENUM ('M', 'F', 'Altre');

CREATE TABLE VOLUNTARIS (
    voluntari_id INTEGER NOT NULL,
    nom VARCHAR(100) NOT NULL,
    cognom1 VARCHAR(100) NOT NULL,
    cognom2 VARCHAR(100),
    edat TIMESTAMP,
    sexe sexe_enum,
    telefon VARCHAR(50) NOT NULL,
    adreca VARCHAR(100) NOT NULL,
    CONSTRAINT PK_VOLUNTARIS PRIMARY KEY (voluntari_id)
);

CREATE TABLE ADMINISTRATIUS (
    voluntari_id INTEGER NOT NULL,
    carrec VARCHAR(100) NOT NULL,
    estudis TEXT NOT NULL,
    CONSTRAINT PK_ADMINISTRATIUS PRIMARY KEY (voluntari_id),
    CONSTRAINT FK_ADMIN_VOL FOREIGN KEY (voluntari_id) REFERENCES VOLUNTARIS(voluntari_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE SANITARIS (
    voluntari_id INTEGER NOT NULL,
    especialitat VARCHAR(100) NOT NULL,
    any_exp INTEGER NOT NULL,
    CONSTRAINT PK_SANITARIS PRIMARY KEY (voluntari_id),
    CONSTRAINT FK_SANI_VOL FOREIGN KEY (voluntari_id) REFERENCES VOLUNTARIS(voluntari_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE SEUS (
    seu_id INTEGER NOT NULL,
    nom VARCHAR(100) NOT NULL,
    nif CHAR(9) UNIQUE NOT NULL,
    adreca VARCHAR(100) NOT NULL,
    telefon VARCHAR(50) NOT NULL,
    president VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SEUS PRIMARY KEY (seu_id)
);

CREATE TABLE SOCIS (
    soci_id INTEGER NOT NULL,
    nom VARCHAR(100) NOT NULL,
    cognom1 VARCHAR(100) NOT NULL,
    cognom2 VARCHAR(100),
    sexe sexe_enum,
    CONSTRAINT PK_SOCIS PRIMARY KEY (soci_id)
);

CREATE TABLE CARNET (
    soci_id INTEGER NOT NULL,
    seu_id INTEGER NOT NULL,
    CONSTRAINT PK_CARNET PRIMARY KEY (soci_id, seu_id),
    CONSTRAINT FK_CARNET_SOCI FOREIGN KEY (soci_id) REFERENCES SOCIS(soci_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_CARNET_SEU FOREIGN KEY (seu_id) REFERENCES SEUS(seu_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ENVIAMENTS (
    enviament_id INTEGER NOT NULL,
    seu_id INTEGER NOT NULL,
    data TIMESTAMP,
    prioritat INTEGER,
    CONSTRAINT PK_ENVIAMENTS PRIMARY KEY (enviament_id),
    CONSTRAINT FK_ENV_SEU FOREIGN KEY (seu_id) REFERENCES SEUS(seu_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ENV_PERSONAL (
    enviament_id INTEGER NOT NULL,
    CONSTRAINT PK_ENV_PERSONAL PRIMARY KEY (enviament_id),
    CONSTRAINT FK_PERSONAL_ENV FOREIGN KEY (enviament_id) REFERENCES ENVIAMENTS(enviament_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ENV_MATERIAL (
    enviament_id INTEGER NOT NULL,
    destinacio VARCHAR(100) NOT NULL,
    qty_productes INTEGER NOT NULL,
    CONSTRAINT PK_ENV_MATERIAL PRIMARY KEY (enviament_id),
    CONSTRAINT FK_MATERIAL_ENV FOREIGN KEY (enviament_id) REFERENCES ENVIAMENTS(enviament_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ALIMENTS (
    enviament_id INTEGER NOT NULL,
    codi_ref VARCHAR(55) UNIQUE NOT NULL,
    caducitat TIMESTAMP NOT NULL,
    liquid BOOLEAN NOT NULL,
    CONSTRAINT PK_ALIMENTS PRIMARY KEY (enviament_id),
    CONSTRAINT FK_ALIMENTS_MAT FOREIGN KEY (enviament_id) REFERENCES ENV_MATERIAL(enviament_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE MEDICAMENTS (
    enviament_id INTEGER NOT NULL,
    caducitat TIMESTAMP NOT NULL,
    alergens VARCHAR(100) NOT NULL,
    oral BOOLEAN NOT NULL,
    perillosa BOOLEAN NOT NULL,
    CONSTRAINT PK_MEDICAMENTS PRIMARY KEY (enviament_id),
    CONSTRAINT FK_MEDIC_MAT FOREIGN KEY (enviament_id) REFERENCES ENV_MATERIAL(enviament_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE AJUDA_HUMANITARIA (
    voluntari_id INTEGER NOT NULL,
    enviament_id INTEGER NOT NULL,
    destinacio VARCHAR(100) NOT NULL,
    data_ini TIMESTAMP NOT NULL,
    data_fi TIMESTAMP,
    CONSTRAINT PK_AJUDA PRIMARY KEY (voluntari_id, enviament_id),
    CONSTRAINT FK_AJUDA_VOL FOREIGN KEY (voluntari_id) REFERENCES VOLUNTARIS(voluntari_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_AJUDA_ENV FOREIGN KEY (enviament_id) REFERENCES ENV_PERSONAL(enviament_id) ON DELETE RESTRICT ON UPDATE CASCADE
);
